### ISSUE TITLE
Complete dadjoke.py search function

### ISSUE THREAD

**Issue by rik079** [rik079/Speasier#10]
I merged  #9 for now, because I didn't want to wait for someone more API-savvy then I to pop up, but it still needs to be fixed one day.

Both functions are now basically a copy of each other, with the search one having a warning that the function isn't complete yet. `dadjoke.Dadjoke` in the first part of the if-statement needs to be changed to a `dadjoke.DadjokeSearch()` and we have to find a way to deal with the different results that can come up, and pick a random one of them.

**Comment by Micro-T** [comment]
I'm starting to work on this. We're still using this API correct? https://icanhazdadjoke.com/api#search-for-dad-jokes

**Comment by rik079** [comment]
Correct. If you're starting to work on it, please assign the issue to yourself (to indicate that you have 'claimed' it) and add the 'in progress' label to show you're actively working on this right now.
