### ISSUE TITLE
Create database table and command to store the channel 

### ISSUE THREAD

**Issue by Worthy-Alpaca** [rik079/Speasier#31]
Links to #2 
I suggest the following table layout:
Column 1: GuildID TEXT NOT NULL UNIQUE
Column 2: ChannelID TEXT NOT NULL
_Maybe, to link a text channel to a voice channel_ 
Column 3: VChannelID TEXT NOT NULL

**Comment by Worthy-Alpaca** [comment]
if we link a voice channel to a text channel then we need to set ChannelID as UNIQUE

**Comment by rik079** [comment]
(Did that, btw ^^)
