### ISSUE TITLE
Store who uses what voice in RAM

### ISSUE THREAD

**Issue by rik079** [rik079/Speasier#40]
So we don't have to constantly query the database on HDD/SSD all the time, reduces latency between enter and the start of the message being sent in the voice channel a bit. I guess the best way to do this is to create a :memory: database, and once a user starts speaking for the first time after the bot has been restarted, a copy of their profile is stored in this DB. this way, we only need to lookup the voice from the DB file outside of memory once, until the bot has to restart

**Comment by Worthy-Alpaca** [comment]
I disagree. I think we should simply do the DB query simultaneously to the API call to Polly. That way we don't need to use RAM.
