### ISSUE TITLE
Chore: update copyright notice

### ISSUE THREAD

**Issue by rik079** [rik079/Speasier#45]
In most files, the copyright notice is `# Copyright (C) Speasy`. Because of the new license, this needs to be changed to `# Copyright (c) 2020 Rik079, Worthy Alpaca, Zibadian, Micro-T. All rights reserved.`

**Comment by Worthy-Alpaca** [comment]
use the search and replace function ;)

**Comment by rik079** [comment]
I'm not saying *how* it should be done, just that it should be done 😃

**Comment by Worthy-Alpaca** [comment]
Done in main.
